export function createTemplateData() {
  return {
    description: "Select one workflow candidate and invoke it.",
    task_name: "control_flows.workflow_selector",
    has_inputs: true,
    template: {
      input: {
        required: false,
        placeholder: "",
        show: true,
        value: "",
        name: "input",
        display_name: "input",
        type: "str",
        list: false,
        field_type: "textarea",
      },
      template: {
        required: true,
        placeholder: "",
        show: false,
        value: "Choose the best workflow for the request.",
        name: "template",
        display_name: "template",
        type: "str",
        list: false,
        field_type: "textarea",
      },
      workflow_ids: {
        required: true,
        placeholder: "",
        show: false,
        value: [],
        name: "workflow_ids",
        display_name: "workflow_ids",
        type: "list",
        list: false,
        field_type: "select",
      },
      llm_model: {
        required: false,
        placeholder: "",
        show: false,
        value: "OpenAI/gpt-4o-mini",
        options: [],
        name: "llm_model",
        display_name: "llm_model",
        type: "str",
        list: false,
        field_type: "select",
      },
      selected_workflow_id: {
        required: true,
        placeholder: "",
        show: false,
        value: "",
        name: "selected_workflow_id",
        display_name: "selected_workflow_id",
        type: "str",
        list: false,
        field_type: "",
        is_output: true,
      },
      selection_reason: {
        required: true,
        placeholder: "",
        show: false,
        value: "",
        name: "selection_reason",
        display_name: "selection_reason",
        type: "str",
        list: false,
        field_type: "textarea",
        is_output: true,
      },
      output: {
        required: true,
        placeholder: "",
        show: false,
        value: {},
        name: "output",
        display_name: "output",
        type: "dict",
        list: false,
        field_type: "",
        is_output: true,
      },
    },
  }
}
